name: workflow-with-dynamic_matrix
on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: windows-latest
    outputs:
      repository: ${{ steps.json.outputs.repository }}
    steps:
      - name: build matrix
        id: json        
        run: |       
          $repository='{"repository": [".\\MDSng\\MDSng_GUI\\MDSng_GUI_CrashDataManagement\\MDSng_GUI_CrashDataManagement.sln",".\\MDSng\\MDSng_GUI\\MDSng_GUI_GUI\\MDSng_GUI_GUI.sln",".\\ReportFolder\\repo3.sln",".\\ReportFolder\\repo4.sln"] }'
          echo "repository=$repository" >> "$ENV:GITHUB_OUTPUT"
  show-summary:
    needs: prepare
    runs-on: windows-latest
    steps:
     - name: Prepare input
       id: prepareInput
       run: |
         $input = "file://bosch.com/dfsrb/DfsDE/DIV/CS/DE_CS$/Prj/PS/Support/Tools/MDSng_64Bit/ContinuousIntegration/GitHub_Builds/208-create-ranorex-cicd-pipeline/9_1/TestResults/"
         echo "myInput=$input" >> $ENV:GITHUB_OUTPUT
     - name: Summary
       run: |       
        echo "${{ steps.prepareInput.outputs.myInput }}"
        echo "[Here]('${{ steps.prepareInput.outputs.myInput }}') File Path" >> $ENV:GITHUB_STEP_SUMMARY
  run-matrix:
    needs: prepare
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{ fromJson(needs.prepare.outputs.repository) }}
    steps:
      - run: |
          echo "${{ matrix.repository }}"
          echo "### Hello world! :rocket:" >> $ENV:GITHUB_STEP_SUMMARY
          
