name: workflow-with-dynamic_matrix
on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: windows-latest
    outputs:
      repository: ${{ steps.json.outputs.repository }}
    steps:
      - name: build matrix
        id: json        
        run: |       
          $repository='{"repository": [".\\ReportFolder\\repo1.sln",".\\ReportFolder\\repo2.sln",".\\ReportFolder\\repo3.sln",".\\ReportFolder\\repo4.sln"] }'
          echo "repository=$repository" >> "$ENV:GITHUB_OUTPUT"

  run-matrix:
    needs: prepare
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix: ${{ fromJson(needs.prepare.outputs.repository) }}
    steps:
      - run: echo "${{ matrix.repository }}"
